spring:
  main:
    # Indique à Spring d'utiliser un serveur web Réactif (Netty),
    # ce qui est OBLIGATOIRE pour Spring Cloud Gateway
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          # Active la découverte automatique des routes via Eureka.
          # C'est la "magie" : la Gateway va automatiquement créer
          # des routes pour 'MSPRODUCTS', 'CONFIGSERVER', etc.
          enabled: true

      # --- C'EST LA SECTION À AJOUTER ---
      globalcors:
        cors-configurations:
          "[/**]": # Appliquer cette règle à tous les chemins
            allowed-origins: "http://localhost:4200" # L'URL de votre app Angular
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS" # Important pour les requêtes "preflight"
            allowed-headers: "*" # Autorise tous les en-têtes (comme 'Authorization' et 'Content-Type')
            allow-credentials: true # Autorise l'envoi d'identifiants (nécessaire pour l'authentification)
      # --- FIN DE LA SECTION À AJOUTER ---
